"""Added unique to Email

Revision ID: 390a29932968
Revises: 336e2160c8ce
Create Date: 2024-01-18 12:04:21.741380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390a29932968'
down_revision = '336e2160c8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email_constraint', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email_constraint', type_='unique')

    # ### end Alembic commands ###
